/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const ProfileLazyImport = createFileRoute('/profile')()
const LogoutLazyImport = createFileRoute('/logout')()
const LoginLazyImport = createFileRoute('/login')()
const HelpLazyImport = createFileRoute('/help')()
const FaqLazyImport = createFileRoute('/faq')()
const BooksFindLazyImport = createFileRoute('/books/find')()
const BooksAllLazyImport = createFileRoute('/books/all')()
const BooksIdLazyImport = createFileRoute('/books/$id')()

// Create/Update Routes

const ProfileLazyRoute = ProfileLazyImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))

const LogoutLazyRoute = LogoutLazyImport.update({
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/logout.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const HelpLazyRoute = HelpLazyImport.update({
  path: '/help',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/help.lazy').then((d) => d.Route))

const FaqLazyRoute = FaqLazyImport.update({
  path: '/faq',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/faq.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BooksFindLazyRoute = BooksFindLazyImport.update({
  path: '/books/find',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/books/find.lazy').then((d) => d.Route))

const BooksAllLazyRoute = BooksAllLazyImport.update({
  path: '/books/all',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/books/all.lazy').then((d) => d.Route))

const BooksIdLazyRoute = BooksIdLazyImport.update({
  path: '/books/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/books/$id.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqLazyImport
      parentRoute: typeof rootRoute
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLazyImport
      parentRoute: typeof rootRoute
    }
    '/books/$id': {
      id: '/books/$id'
      path: '/books/$id'
      fullPath: '/books/$id'
      preLoaderRoute: typeof BooksIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/books/all': {
      id: '/books/all'
      path: '/books/all'
      fullPath: '/books/all'
      preLoaderRoute: typeof BooksAllLazyImport
      parentRoute: typeof rootRoute
    }
    '/books/find': {
      id: '/books/find'
      path: '/books/find'
      fullPath: '/books/find'
      preLoaderRoute: typeof BooksFindLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  FaqLazyRoute,
  HelpLazyRoute,
  LoginLazyRoute,
  LogoutLazyRoute,
  ProfileLazyRoute,
  BooksIdLazyRoute,
  BooksAllLazyRoute,
  BooksFindLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/faq",
        "/help",
        "/login",
        "/logout",
        "/profile",
        "/books/$id",
        "/books/all",
        "/books/find"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/faq": {
      "filePath": "faq.lazy.tsx"
    },
    "/help": {
      "filePath": "help.lazy.tsx"
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/logout": {
      "filePath": "logout.lazy.tsx"
    },
    "/profile": {
      "filePath": "profile.lazy.tsx"
    },
    "/books/$id": {
      "filePath": "books/$id.lazy.tsx"
    },
    "/books/all": {
      "filePath": "books/all.lazy.tsx"
    },
    "/books/find": {
      "filePath": "books/find.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
